INSERT INTO MNS_ROC_APPLICANTS_ATTACH(RAA_APPLICATION_NO, RAA_SERIAL_NO, RAA_LOCAL_FNAME, RAA_ORG_FNAME, RAA_FILE_PATH, RAA_DT_UPLOADED)
values ('20230101RC004599', '1', 'BRUME', 'MNS', 'SRC/TEST', to_date('09-MAR-22', 'DD-MON-RR'));
COMMIT;