INSERT INTO MNS_ROC_APPLICANTS_CONTACT(RAC_APPLICATION_NO, RAC_SERIAL_NO, RAC_FNAME, RAC_LNAME, RAC_JOBTITLE, RAC_TEL, RAC_FAX, RAC_EMAIL, RAC_MAIN)
values ('20230101RC004599', '1', 'BRUME', 'LOVE',  'SE', '34344', '344', 'TEST@GMAIL@COM', 'Y');
COMMIT;