INSERT into MNS_ROC_APPLICANTS (APPLICATION_NO, PERSON, TITLE, TITLE_DESCRIPTION, NAME, OTHER_NAMES, CONTACT_NAME, CONTACT_JOB_TITLE, CITIZEN, ID_TYPE, ID_DESCRIPTION, CTY_CODE, ID_NO, ADDRESS1, ADDRESS2, ADDRESS3, ADDRESS4, ADDRESS5, TEL, FAX, EMAIL, SCENTRE_FLAG, SCENTRE_TYPE, STATUS, REMARKS, IP_ADDRESS, CREATE_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, FIRSTNAME, NATURE_OF_BUSINESS, TYPE, OTHERS, COMPANY_FILE, ID, NID_PASSPORT)
values ('20230101RC0004599', 'F', 'SOFTWARE ENGINEER', null, 'MNS', null, 'BRUME',
        null, 'N', 'NID', null, null, '909990', '21 SILICON VALLEY', 'EBENE', 'ROSEHILL', 'N', null, '9089002', '727187',
        'test@gmail.com', 'N', null, 'NW', null, '127.0.0.1', to_date('09-MAR-22', 'DD-MON-RR'), 'BRUME', to_date('09-MAR-22', 'DD-MON-RR'), 'BRUME', null, 'S1', 'ERGBG', 'MSAJAKA', 'N',
        'AIS12332');
COMMIT;

CREATE SEQUENCE  "MNS_SEQ_ROC_APPL"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 5 START WITH 3;
