INSERT INTO MNS_ROC_APPLICANTS_ADM(RAA_APPLICATION_NO, RAA_SERIAL_NO, RAA_FNAME, RAA_LNAME, RAA_JOBTITLE, RAA_DEPT, RAA_TEL, RAA_FAX, RAA_EMAIL, RAA_MAIN)
values ('20230101RC004599', '1', 'BRUME', 'LOVE', 'SE', 'SE', '34344', '344', 'TEST@GMAIL@COM', 'Y');
COMMIT;