INSERT INTO MNS_ROC_APPLICANTS_USER(RAU_APPLICATION_NO, RAU_SERIAL_NO, RAU_FNAME, RAU_LNAME, RAU_JOBTITLE, RAU_TEL, RAU_FAX, RAU_EMAIL, RAU_MAIN)
values ('20230101RC004599', '1', 'BRUME', 'LOVE', 'SE',  '34344', '344', 'TEST@GMAIL@COM', 'Y');
COMMIT;